version: "3"
services:
  redis:
    image: redis:4
    expose:
      - "6379"
    networks:
      - api_network
  api:
    build:
      context: .
      dockerfile: DockerfileTest
    networks:
      - api_network
    restart: "no"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis:redis

networks:
  api_network:
