version: "3"
services:
  redis:
    image: redis:4
    networks:
      - api_network
  api:
    build:
      context: .
      dockerfile: DockerfileTest
    networks:
      - api_network
    restart: "no"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

networks:
  api_network:
